{
 "title": "ODOO Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Modules",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT state, COUNT(state) FROM ir_module_module GROUP BY state ORDER BY state "
    }
   ]
  },
  {
   "title": "Number of users",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM res_users LIMIT 50 "
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT id, login, active FROM res_users ORDER BY id LIMIT 50 "
    }
   ]
  }
 ]
}